trigger:
- master

pool:
  vmImage: windows-latest

steps:
- checkout: self
  fetchDepth: 0

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarQube Connection'
    organization: 'culturebmo'
    scannerMode: 'MSBuild'
    projectKey: 'CultureBMo_ProLexia'
    projectName: 'ProLexia'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_11_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'